# -*- coding: utf-8 -*-
"""chamgingfromcdimtopng.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jrJW-6HFyRgPg9GFbfadx4Oy1DrqHNog
"""

pip install dicom

pip install pydicom

pip install opencv-python

pip install pillow

pip install pandas

import pydicom as dicom
import os
import cv2
import PIL # optional
# make it True if you want in PNG format
PNG = True
# Specify the .dcm folder path
folder_path = "/content/sample_data/covid"
# Specify the output jpg/png folder path
jpg_folder_path = "/content/sample_data/pngFolder"
images_path = os.listdir(folder_path)
for n, image in enumerate(images_path):
    ds = dicom.dcmread(os.path.join(folder_path, image))
    pixel_array_numpy = ds.pixel_array
    image = image.replace('.dcm', '.png')
    cv2.imwrite(os.path.join(jpg_folder_path, image), pixel_array_numpy)
    print('Image {} converted'.format(n))