# -*- coding: utf-8 -*-
"""chamgingfromniitopng.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PnF0wN3dYhIIuQRRp9UwewwjxbINt9dS
"""

import cv2
import glob
from PIL import Image
import os
import numpy as np
import imageio
from PIL import Image
import cv2
from nibabel.testing import data_path
example_filename = os.path.join(data_path, '/content/coronacases_org_002.nii')
import nibabel as nib
img = nib.load(example_filename)
img.shape

img.shape

number_of_images=img.shape[2]
number_of_images

img.get_data_dtype() == np.dtype(np.int16)

img.affine.shape

a= np.array(img.dataobj[:, :, 190])

a.shape

a

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

image = cv2.rotate(a, cv2.cv2.ROTATE_90_COUNTERCLOCKWISE)
plt.gray()
plt.imshow(image)

for i in range (img.shape[2]):
     a= np.array(img.dataobj[:, :, i])
     image = cv2.rotate(a, cv2.cv2.ROTATE_90_COUNTERCLOCKWISE)  
     name = 'corona' + str(i) + '.png'
     plt.imsave(name, image)