# -*- coding: utf-8 -*-
"""FromPNGtoNII.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196Nr6lzXsYhLNVlofHCP-8WUS8suLABp
"""

pip install nibabel

import glob
import cv2
import numpy as np
import nibabel as nib


cv_img = []
for img in glob.glob("/content/*.png"):
    n= cv2.imread(img,0)
    cv_img.append(n)

np.array(cv_img).shape

PNG_folder_path="/content/"

converted_array = np.array(cv_img, np.float32) # You need to replace normal array by yours
affine = np.eye(4)
nifti_file = nib.Nifti1Image(converted_array, affine)

nib.save(nifti_file, 'corona_image.nii') # Here you put the path + the extionsion 'nii' or 'nii.gz'